#!/bin/bash

# : <<'#__ATOM__'

#
# 10k game development installer
# @copyright 2017-2018 YuTanaka@AmuseOne
# @license MIT
#

cd ~

# __UPDATE_APTGET__
sudo apt-get update

#__NODE__
# 参考URL http://qiita.com/seibe/items/36cef7df85fe2cefa3ea

echo -Install Node-

sudo apt-get install -y nodejs npm

sudo npm cache clean
sudo npm install n -g

sudo n stable
sudo ln -sf /usr/local/bin/node /usr/bin/node

sudo apt-get purge -y nodejs npm

echo -Install Node done-

#__ATOM__
echo -Install Atom-

wget -q -O - https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'
sudo apt-get update

sudo apt-get install atom -y

## install package
apm install atom-html-preview emmet atom-ternjs

echo -Install Atom done-

#__Chrome__
echo -Install Google Chrome-

sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
sudo apt-get update

sudo apt-get install google-chrome-stable -y

sudo apt-get install -f -y

echo -Install Google Chrome done-

#__http_server__
echo -Install http-server-

sudo npm i -g http-server

echo -Install http-server done-

# --------------------

#__Grunt__
echo -Install Grunt-

sudo npm install -g grunt-cli

echo -Install Grunt done-


#__Phaser__
echo -Install Phaser-

mkdir phaser
cd phaser
git clone https://github.com/photonstorm/phaser-ce.git phaser

#__Phaser_Examples__
git clone https://github.com/photonstorm/phaser-examples.git
cd phaser-examples
npm i
grunt

#__Phaser_Template_Simple__
cd ~/phaser
git clone https://github.com/am1tanaka/phaser-template-simple.git
cd phaser-template-simple
npm i
chmod 700 fetch
./fetch
rm fetch

#__Phaser_Boilerplate__
cd ~/phaser
git clone https://github.com/goldfire/phaser-boilerplate.git
cd phaser-boilerplate
npm i
npm i tern-phaser
npm run dev:server
npm run dev:phaser
echo -Install Phaser done-

#__MAKE_NEW_PHASER_PROJECT_FILE__
cd ~/phaser
wget -N --no-check-certificate https://raw.githubusercontent.com/am1tanaka/10k-gamedev/master/phaser-new
chmod 700 phaser-new
wget -N --no-check-certificate https://raw.githubusercontent.com/am1tanaka/10k-gamedev/master/phaser-new-smpl
chmod 700 phaser-new-smpl

#__PHP__
echo -Install PHP7-

echo y | sudo apt install php7.0-cli
sudo apt update

echo -Install PHP7 done-

cd ~

#__FINISH__
sudo apt autoremove -y
chmod 600 ~/install-gdev

